### ISSUE TITLE
Configurable Chat Models

### ISSUE THREAD

**Issue by jayminwest** [jayminwest/kota-ai#15]
# Configurable Chat Models

## Overview
Currently, the KOTA AI chat interface uses a hardcoded model configuration when interacting with the Anthropic API. To make the system more flexible and future-proof, we should implement a configuration system that allows users to select and configure different AI models.

## Requirements

1. Create a `config/models.yaml` file to store model configurations
2. Support multiple model providers (Anthropic, OpenAI, etc.)
3. Allow users to specify default models
4. Include model-specific parameters (temperature, max tokens, etc.)
5. Provide a CLI command to list and select models

### Configuration File Structure
```yaml
models:
  - id: claude-3-opus
    provider: anthropic
    name: "Claude 3 Opus"
    description: "Most powerful Claude model for complex tasks"
    parameters:
      temperature: 0.7
      max_tokens: 4096
    default: true
  
  - id: claude-3-sonnet
    provider: anthropic
    name: "Claude 3 Sonnet"
    description: "Balanced Claude model for most tasks"
    parameters:
      temperature: 0.7
      max_tokens: 4096
    
  - id: gpt-4
    provider: openai
    name: "GPT-4"
    description: "OpenAI's advanced model"
    parameters:
      temperature: 0.7
      max_tokens: 2048
```

### Implementation Tasks

1. Create a model configuration loader class
2. Update the AnthropicService to use the configuration
3. Add support for other providers (OpenAI, etc.)
4. Add CLI commands to:
   - List available models
   - Set default model
   - Show current model configuration
5. Update the persistent chat interface to display and allow selection of models

## Benefits

- Flexibility to use different models without code changes
- Future-proofing for new model releases
- Consistent configuration approach across providers
- Better user experience with model selection options

## Acceptance Criteria

- [ ] Configuration file is loaded on startup
- [ ] Users can list available models
- [ ] Users can change the default model
- [ ] Chat interface shows which model is being used
- [ ] Parameters from the config file are applied to API calls
